[server]
# Railway routes traffic via reverse proxy; bind to all interfaces
address = "0.0.0.0"
# port is provided via CLI as $PORT in Procfile
headless = true
enableCORS = false
enableXsrfProtection = false

[runner]
magicEnabled = false

[browser]
gatherUsageStats = false
